on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{matrix.compiler}}
      CXX: ${{matrix.compiler}}
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: cmake . -GNinja
    - run: ninja
    - run: ninja tests

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: cmake . -GNinja
    - run: ninja
    - run: ninja tests
